/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import Controller.AgendaController;
import Model.Age;
import Model.AgendaTableModel;
import java.io.Writer;
import Model.Servico;
import java.awt.JobAttributes;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author rober
 */
public class Agenda extends javax.swing.JFrame {
    AgendaTableModel tabelmodel = new AgendaTableModel();
    String pathFile = "dados.txt";
    String pathFileTemp = "dadosTemp.txt";
    String readFile = "";
    
    List<Age> list = new ArrayList<>();
    private final TableRowSorter<TableModel> sorter = new TableRowSorter<>(tabelmodel);
    

    private final AgendaController controller;

    /**
     * Creates new form Agenda
     */
    public Agenda() {
        initComponents();
        controller = new AgendaController(this);    
        iniciar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Marcas = new javax.swing.JComboBox<String>();
        jButtonMostrarDados = new javax.swing.JButton();
        jComboBoxPais = new javax.swing.JComboBox<String>();
        jTextFieldID = new javax.swing.JTextField();
        jButtonImportar = new javax.swing.JButton();
        jButtonLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabelID = new javax.swing.JLabel();
        jComboBoxServicos = new javax.swing.JComboBox<String>();
        jLabelObservacao = new javax.swing.JLabel();
        jLabelServicos = new javax.swing.JLabel();
        jLabelPais = new javax.swing.JLabel();
        jLabelMarcas = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        jLabelPlano = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Marcas.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Acura", "BMW", "Citroen", "Chevrolet", "Fiat", "Ford", "Honda", "Hyunda", "Porsche", "Volkswagen" }));
        Marcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcasActionPerformed(evt);
            }
        });
        getContentPane().add(Marcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 280, 60));

        jButtonMostrarDados.setBackground(new java.awt.Color(255, 0, 0));
        jButtonMostrarDados.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonMostrarDados.setText("Mostrar Dados");
        jButtonMostrarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarDadosActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMostrarDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, 140, 50));

        jComboBoxPais.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Afeganistão\tCabul\tÁsia", "África do Sul\tPretória\tÁfrica", "Albânia\tTirana\tEuropa", "Alemanha\tBerlim\tEuropa", "Andorra\tAndorra-a-Velha\tEuropa", "Angola\tLuanda\tÁfrica", "Antiga e Barbuda\tSão João\tAmérica", "Arábia Saudita\tRiade\tÁsia", "Argélia\tArgel\tÁfrica", "Argentina\tBuenos Aires\tAmérica", "Arménia\tErevã\tÁsia", "Austrália\tCamberra\tOceania", "Áustria\tViena\tEuropa", "Azerbaijão\tBacu\tÁsia", "Bahamas\tNassau\tAmérica", "Bangladexe\tDaca\tÁsia", "Barbados\tBridgetown\tAmérica", "Barém\tManama\tÁsia", "Bélgica\tBruxelas\tEuropa", "Belize\tBelmopã\tAmérica", "Benim\tPorto Novo\tÁfrica", "Bielorrússia\tMinsque\tEuropa", "Bolívia\tSucre\tAmérica", "Bósnia e Herzegovina\tSaraievo\tEuropa", "Botsuana\tGaborone\tÁfrica", "Brasil\tBrasília\tAmérica", "Brunei\tBandar Seri Begauã\tÁsia", "Bulgária\tSófia\tEuropa", "Burquina Faso\tUagadugu\tÁfrica", "Burúndi\tBujumbura\tÁfrica", "Butão\tTimbu\tÁsia", "Cabo Verde\tPraia\tÁfrica", "Camarões\tIaundé\tÁfrica", "Camboja\tPnom Pene\tÁsia", "Canadá\tOtava\tAmérica", "Catar\tDoa\tÁsia", "Cazaquistão\tAstana\tÁsia", "Chade\tJamena\tÁfrica", "Chile\tSantiago\tAmérica", "China\tPequim\tÁsia", "Chipre\tNicósia\tEuropa", "Colômbia\tBogotá\tAmérica", "Comores\tMoroni\tÁfrica", "Congo-Brazzaville\tBrazavile\tÁfrica", "Coreia do Norte\tPionguiangue\tÁsia", "Coreia do Sul\tSeul\tÁsia", "Cosovo\tPristina\tEuropa", "Costa do Marfim\tIamussucro\tÁfrica", "Costa Rica\tSão José\tAmérica", "Croácia\tZagrebe\tEuropa", "Cuaite\tCidade do Cuaite\tÁsia", "Cuba\tHavana\tAmérica", "Dinamarca\tCopenhaga\tEuropa", "Dominica\tRoseau\tAmérica", "Egito\tCairo\tÁfrica", "Emirados Árabes Unidos\tAbu Dabi\tÁsia", "Equador\tQuito\tAmérica", "Eritreia\tAsmara\tÁfrica", "Eslováquia\tBratislava\tEuropa", "Eslovénia\tLiubliana\tEuropa", "Espanha\tMadrid\tEuropa", "Essuatíni\tLobamba\tÁfrica", "Estado da Palestina\tJerusalém Oriental\tÁsia", "Estados Unidos\tWashington, D.C.\tAmérica", "Estónia\tTalim\tEuropa", "Etiópia\tAdis Abeba\tÁfrica", "Fiji\tSuva\tOceania", "Filipinas\tManila\tÁsia", "Finlândia\tHelsínquia\tEuropa", "França\tParis\tEuropa", "Gabão\tLibreville\tÁfrica", "Gâmbia\tBanjul\tÁfrica", "Gana\tAcra\tÁfrica", "Geórgia\tTebilíssi\tÁsia", "Granada\tSão Jorge\tAmérica", "Grécia\tAtenas\tEuropa", "Guatemala\tCidade da Guatemala\tAmérica", "Guiana\tGeorgetown\tAmérica", "Guiné\tConacri\tÁfrica", "Guiné Equatorial\tMalabo\tÁfrica", "Guiné-Bissau\tBissau\tÁfrica", "Haiti\tPorto Príncipe\tAmérica", "Honduras\tTegucigalpa\tAmérica", "Hungria\tBudapeste\tEuropa", "Iémen\tSaná\tÁsia", "Ilhas Marechal\tMajuro\tOceania", "Índia\tNova Déli\tÁsia", "Indonésia\tJacarta\tÁsia", "Irão\tTeerão\tÁsia", "Iraque\tBagdade\tÁsia", "Irlanda\tDublim\tEuropa", "Islândia\tReiquiavique\tEuropa", "Israel\tJerusalém\tÁsia", "Itália\tRoma\tEuropa", "Jamaica\tKingston\tAmérica", "Japão\tTóquio\tÁsia", "Jibuti\tJibuti\tÁfrica", "Jordânia\tAmã\tÁsia", "Laus\tVienciana\tÁsia", "Lesoto\tMaseru\tÁfrica", "Letónia\tRiga\tEuropa", "Líbano\tBeirute\tÁsia", "Libéria\tMonróvia\tÁfrica", "Líbia\tTrípoli\tÁfrica", "Listenstaine\tVaduz\tEuropa", "Lituânia\tVílnius\tEuropa", "Luxemburgo\tLuxemburgo\tEuropa", "Macedónia do Norte\tEscópia\tEuropa", "Madagáscar\tAntananarivo\tÁfrica", "Malásia\tCuala Lumpur\tÁsia", "Maláui\tLilôngue\tÁfrica", "Maldivas\tMalé\tÁsia", "Mali\tBamaco\tÁfrica", "Malta\tValeta\tEuropa", "Marrocos\tRebate\tÁfrica", "Maurícia\tPorto Luís\tÁfrica", "Mauritânia\tNuaquechote\tÁfrica", "México\tCidade do México\tAmérica", "Mianmar\tNepiedó\tÁsia", "Micronésia\tPaliquir\tOceania", "Moçambique\tMaputo\tÁfrica", "Moldávia\tQuixinau\tEuropa", "Mónaco\tMónaco\tEuropa", "Mongólia\tUlã Bator\tÁsia", "Montenegro\tPodgoritsa\tEuropa", "Namíbia\tVinduque\tÁfrica", "Nauru\tIarém\tOceania", "Nepal\tCatmandu\tÁsia", "Nicarágua\tManágua\tAmérica", "Níger\tNiamei\tÁfrica", "Nigéria\tAbuja\tÁfrica", "Noruega\tOslo\tEuropa", "Nova Zelândia\tWellington\tOceania", "Omã\tMascate\tÁsia", "Países Baixos\tAmesterdão\tEuropa", "Palau\tNgerulmud\tOceania", "Panamá\tCidade do Panamá\tAmérica", "Papua Nova Guiné\tPorto Moresby\tOceania", "Paquistão\tIslamabade\tÁsia", "Paraguai\tAssunção\tAmérica", "Peru\tLima\tAmérica", "Polónia\tVarsóvia\tEuropa", "Portugal\tLisboa\tEuropa", "Quénia\tNairóbi\tÁfrica", "Quirguistão\tBisqueque\tÁsia", "Quiribáti\tTaraua do Sul\tOceania", "Reino Unido\tLondres\tEuropa", "República Centro-Africana\tBangui\tÁfrica", "República Checa\tPraga\tEuropa", "República Democrática do Congo\tQuinxassa\tÁfrica", "República Dominicana\tSão Domingos\tAmérica", "Roménia\tBucareste\tEuropa", "Ruanda\tQuigali\tÁfrica", "Rússia\tMoscovo\tEuropa", "Salomão\tHoniara\tOceania", "Salvador\tSão Salvador\tAmérica", "Samoa\tApia\tOceania", "Santa Lúcia\tCastries\tAmérica", "São Cristóvão e Neves\tBasseterre\tAmérica", "São Marinho\tSão Marinho\tEuropa", "São Tomé e Príncipe\tSão Tomé\tÁfrica", "São Vicente e Granadinas\tKingstown\tAmérica", "Seicheles\tVitória\tÁfrica", "Senegal\tDacar\tÁfrica", "Serra Leoa\tFreetown\tÁfrica", "Sérvia\tBelgrado\tEuropa", "Singapura\tSingapura\tÁsia", "Síria\tDamasco\tÁsia", "Somália\tMogadíscio\tÁfrica", "Sri Lanca\tSri Jaiavardenapura-Cota\tÁsia", "Sudão\tCartum\tÁfrica", "Sudão do Sul\tJuba\tÁfrica", "Suécia\tEstocolmo\tEuropa", "Suíça\tBerna\tEuropa", "Suriname\tParamaribo\tAmérica", "Tailândia\tBanguecoque\tÁsia", "Taiuã\tTaipé\tÁsia", "Tajiquistão\tDuchambé\tÁsia", "Tanzânia\tDodoma\tÁfrica", "Timor-Leste\tDíli\tOceania", "Togo\tLomé\tÁfrica", "Tonga\tNucualofa\tOceania", "Trindade e Tobago\tPorto de Espanha\tAmérica", "Tunísia\tTunes\tÁfrica", "Turcomenistão\tAsgabate\tÁsia", "Turquia\tAncara\tÁsia", "Tuvalu\tFunafuti\tOceania", "Ucrânia\tQuieve\tEuropa", "Uganda\tCampala\tÁfrica", "Uruguai\tMontevideu\tAmérica", "Usbequistão\tTasquente\tÁsia", "Vanuatu\tPorto Vila\tOceania", "Vaticano\tVaticano\tEuropa", "Venezuela\tCaracas\tAmérica", "Vietname\tHanói\tÁsia", "Zâmbia\tLusaca\tÁfrica", "Zimbábue\tHarare\tÁfrica" }));
        jComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 270, 280, 60));
        getContentPane().add(jTextFieldID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 280, 50));

        jButtonImportar.setBackground(new java.awt.Color(153, 153, 255));
        jButtonImportar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonImportar.setText("Importar\n");
        jButtonImportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImportarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonImportar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, 310, 50));

        jButtonLimpar.setBackground(new java.awt.Color(255, 0, 0));
        jButtonLimpar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 310, 160, 50));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 310, 190));

        jLabelID.setForeground(new java.awt.Color(255, 255, 255));
        jLabelID.setText("ID");
        getContentPane().add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, -1, -1));

        jComboBoxServicos.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Elias", "Yuri", "Robert" }));
        jComboBoxServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxServicosActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 280, 60));

        jLabelObservacao.setForeground(new java.awt.Color(255, 255, 255));
        jLabelObservacao.setText("Descrição");
        getContentPane().add(jLabelObservacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, -1, -1));

        jLabelServicos.setForeground(new java.awt.Color(255, 255, 255));
        jLabelServicos.setText("Serviços");
        getContentPane().add(jLabelServicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, -1, -1));

        jLabelPais.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPais.setText("Pais\n");
        getContentPane().add(jLabelPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, -1));

        jLabelMarcas.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMarcas.setText("Marcas ");
        getContentPane().add(jLabelMarcas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Serviços", "Marcas", "País", "Descricão"
            }
        ));
        jScrollPane2.setViewportView(TableAgendamentos);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 700, 210));

        jLabelPlano.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/Agenda-PainelFundo.png"))); // NOI18N
        jLabelPlano.setText("jLabel2");
        getContentPane().add(jLabelPlano, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 870, 660));

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/imagens/ImporteCarros.png"))); // NOI18N
        getContentPane().add(jLabelFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcasActionPerformed

    private void jComboBoxServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxServicosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxServicosActionPerformed

    private void jComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPaisActionPerformed

    private void jButtonImportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImportarActionPerformed
        if(jTextFieldID.getText().isEmpty()){
        dialog("Digite o ID para importar");
        jTextFieldID.requestFocus();
        }
        else if(jTextArea1.getText().isEmpty()){
        dialog("Digite a descrição para impotar");
        jTextArea1.requestFocus();
        }
        try {
            salvarDados();
        } catch (IOException ex) {
            Logger.getLogger(Agenda.class.getName()).log(Level.SEVERE, null, ex);
        }
        colocarDados();
    }//GEN-LAST:event_jButtonImportarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        limparDados();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonMostrarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarDadosActionPerformed
       mostrarDados();
    }//GEN-LAST:event_jButtonMostrarDadosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Agenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Marcas;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JButton jButtonImportar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonMostrarDados;
    private javax.swing.JComboBox<String> jComboBoxPais;
    private javax.swing.JComboBox<String> jComboBoxServicos;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelMarcas;
    private javax.swing.JLabel jLabelObservacao;
    private javax.swing.JLabel jLabelPais;
    private javax.swing.JLabel jLabelPlano;
    private javax.swing.JLabel jLabelServicos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldID;
    // End of variables declaration//GEN-END:variables

    private void iniciar() {
        this.controller.atualizarTabela();
    }

    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }
    public void colocarDados(){
       DefaultTableModel dtmCadastros; 
       dtmCadastros = (DefaultTableModel) TableAgendamentos.getModel();
       
       Object[] dados = {jTextFieldID.getText(),
              jComboBoxServicos.getSelectedItem().toString(),
              Marcas.getSelectedItem().toString(),
              jComboBoxPais.getSelectedItem().toString(),
              jTextArea1.getText().toString()};
              
       
            dtmCadastros.addRow(dados);
           
   }
   private void salvarDados() throws FileNotFoundException, IOException{
        
        
        String save = jTextFieldID.getText() + ";" + jComboBoxServicos.getSelectedItem() + ";" + Marcas.getSelectedItem() + ";" + jComboBoxPais.getSelectedItem() + ";" + jTextArea1.getText();
            OutputStream os = new FileOutputStream("dados.txt");
            Writer wr = new OutputStreamWriter(os);
            BufferedWriter br = new BufferedWriter(new FileWriter(pathFile,true));
            
            br.write(save);
            br.newLine();
            br.close();
    
    
        }
   private void dialog(String text){
       
       JOptionPane.showMessageDialog(rootPane, text);
   }
   
    public void limparDados(){
    
          jTextFieldID.setText("");
          jComboBoxServicos.setSelectedItem("");
          Marcas.setSelectedItem("");
          jComboBoxPais.setSelectedItem("");
          jTextArea1.setText("");
    }
   

   private void mostrarDados() {
        try {
            list.clear();
            String readLine;
            File file = new File(pathFile);
            if (!file.exists()) {
                file.createNewFile();
            }
            BufferedReader bufReader;
            try (FileReader reader = new FileReader(file)) {
                bufReader = new BufferedReader(reader);
                while ((readLine = bufReader.readLine()) != null) {
                    if (readLine.equals("")) {
                        continue;
                    }
                    String[] splitData = readLine.split(";");
                    Age cd = new Age();
                    cd.setID(splitData[0]);
                    cd.setServicos(splitData[1]);
                    cd.setMarcas(splitData[2]);
                    cd.setPais(splitData[3]);
                    cd.setDescricao(readLine);
                    
                    list.add(cd);
                }
                tabelmodel.setList(list);
                TableAgendamentos.setModel(tabelmodel);
            }
            bufReader.close();
        } catch (IOException ex) {
            Logger.getLogger(Cadastro.class.getName()).log(Level.SEVERE, null, ex);
        }
}
    }
    

   
   
    

